# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac16011b01b8345d3768829289e75a2b678de95057853f7d9b785e70d36e579c41b6ecdb0d4dcae745bd011aa6f710e5a7d9ae217b17a1726cc54cc95a0da2b9

test:
  secret_key_base: 7ebf3e69400d2b08dc7b6bc4cd6aedd78097f609b4ced2865e13865498525b0983045ecc2a63cee4ceef301eaf6242ce27f859700bfc9b29fee37c3e5c82582c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
