# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7cdc943990a1ac9662133fbda366bb710c3017782160f0da1df385b29f638873df7c8a45b82a436962e6d0757e7cf703abfb478163ad9a31ec832feb316719a

test:
  secret_key_base: 7e072b2714e6cc7d4487df53d28f62f41d7499f789597fe47c9b3476565173f1f7d50b6e6db169f5ffbc0992e6a99ace3e2ce5326709051080e7564260c97b62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
